version: '3.7'
services:
  crud-database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: crud_db
    container_name: crud-database

    ports:
      - "5432:5432"